- imagetool/src/main/java/com/oracle/weblogic/imagetool/api/model/AbstractFile.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/WLSCommandLine.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java
It can be confusing for the user when they provide -jdkversion instead of -jdkVersion, and the operation ignores the user's input and takes the default JDK version instead without warnings or errors.
> Fail CREATE operation when bad argument is provided

- imagetool/src/main/resources/docker-files/Dockerfile.ph
For OPatch patch, ignore system prerequisites for cases where images built on a machine with no swap space
> ignore system prerequisites for opatch patch

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java
- imagetool/src/main/resources/docker-files/Create_Image.mustache
- imagetool/src/main/resources/probe-env/test-create-env.sh
- imagetool/src/main/resources/probe-env/test-update-env.sh
If JAVA_HOME is detected in the environment of the base image, create image will skip the Java installation.  fixes #28
> skip Java install if base image already has Java installed

- .idea/codeStyles/Project.xml
- README.md
- imagetool/src/main/bin/logging.properties
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/ImageOperation.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java
- imagetool/src/main/resources/docker-files/Create_Image.mustache
- imagetool/src/main/resources/docker-files/Update_Image.mustache
- site/create-image.md
- site/update-image.md
Added the ability to create a domain during the UPDATE operation of the Image Tool.  Prior to this enhancement, the update phase could only be used to apply WebLogic patches to an existing image.
> Add WDT capability to UPDATE operation

- README.md
- imagetool/src/main/bin/logging.properties
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/WdtOperation.java
- imagetool/src/main/resources/docker-files/Create_Image.mustache
- imagetool/src/main/resources/docker-files/Update_Image.mustache
- site/update-image.md
Add WDT commands, update and deploy, to Image Tool Update
> Enhance Update operation with additional WDT operations

- imagetool/src/main/resources/docker-files/Create_Image.mustache
- imagetool/src/main/resources/docker-files/Update_Image.mustache
This change is only precautionary.  The validate tool only uses the domain type to locate the correct version of WLST.  In various versions of WLS, the JRF and WLS versions of WLST were in different folders.  Post 12.2.1, WLST is in the same location for both installers.
> pass domain type to WDT validate for domain only

- imagetool/src/main/resources/docker-files/Create_Image.mustache
To keep Image Tool images in line with Java server JRE images, this change will leave the TAR and GZIP tools installed in the final image.  Previously, these tools were installed in an intermediate layer, and then left out of the final image.
> keep tar and gzip tools installed in the final image

- imagetool/pom.xml
- pom.xml
Similar to other projects in this organization, the zip installer should not have a version number in the filename.
> remove version number from zip installer

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/ImageOperation.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java
- imagetool/src/main/resources/docker-files/Create_Image.mustache
- imagetool/src/main/resources/docker-files/Update_Image.mustache
Default for modelOnly validation will be method=lax for WDT validate which will skip property and file validation during docker build.  Missing values will show up as info messages and the build will not fail.  To revert to original behavior, run with "--wdtStrictValidation"
> default to new lax validation for WDT validate with model only

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/cache/AddPatchEntry.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java
> Correct file descriptor leak for zip

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java
When using update with wdtOnly option without request for any patches, we still check for opatch in the cache.  This change is to avoid the check.
> check for opatch only when we need to apply patch

- imagetool/src/main/java/com/oracle/weblogic/imagetool/api/model/CachedFile.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
- imagetool/src/main/resources/ImageTool.properties
- site/create-image.md
- site/rebase-image.md
- site/update-image.md
Added ability for user to add custom files to the build context so that additional build commands can utilize those files (like COPY or ADD).  Fixes #106
> additional build files support

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/WdtOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java
- imagetool/src/main/resources/docker-files/Create_Image.mustache
- imagetool/src/main/resources/docker-files/Rebase_Image.mustache
- imagetool/src/main/resources/docker-files/Update_Image.mustache
If the WDT zip file is other than weblogic-deploy.zip, docker build copy failed.
> allow WDT installer name to be other than weblogic-deploy.zip

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/RebaseImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java
- imagetool/src/main/resources/ImageTool.properties
- site/create-image.md
- site/rebase-image.md
- site/update-image.md
Fixes #128.  --additionalBuildFiles option allows the user to add additional files to the build context that can be used with custom build commands in --addtionalBuildCommands like COPY or ADD.  This enhancement adds support for folders so that the user can pass a folder name to the additionalBuildFiles option.  The folder name and its contents are then copied to the build content "files" folder.
> added support for folders using additionalBuildFiles feature

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java
- imagetool/src/main/resources/ImageTool.properties
WDT does not have an option to run RCU for updateDomain.  Run RCU can only be used with WDT createDomain.
> Prevent RunRCU when not in CREATE

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cachestore/PatchFile.java
The download URL path for patches is incorrect due to not passing the path through String.format.
> xpath for download URL is not populated with patch version

- site/create-image.md
- site/rebase-image.md
- site/update-image.md
--buildNetwork for Docker --network
and
--wdtEncryptionKey for WDT -use_encryption
> Updated documentation for release 1.8.2

- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java
Default to http:// when it is not provided in the http_proxy or https_proxy environment variable
> Fix proxy scheme problem to only add scheme when no scheme is provided.

- imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/DefaultResponseFile.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/FmwInstallerType.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/InstallerType.java
- site/create-image.md
- site/rebase-image.md
OHS is not an OUI installer, and does not require Java.  OHS is not a good fit for the WebLogic Image Tool.
> remove option to install OHS product

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/RebaseImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/WdtOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerBuildCommand.java
- site/create-image.md
- site/rebase-image.md
- site/update-image.md
Fixes #146 
Add an option to enable --pull for the Docker build command.  Enabling the pull option will attempt to pull a newer version of base images during the build.
> added --pull option for the docker build

- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java
- imagetool/src/main/resources/ImageTool.properties
By default, Docker leaves containers around indefinitely.  During the imagetool update flow, the tool creates a new container from the image to be updated in order to check the version of WLS and the patches installed.   After exiting, this container is no longer needed.  Adding "--rm" will tell Docker to remove the container after it exits.
> cleanup docker container created during update

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/RebaseImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java
- imagetool/src/main/resources/ImageTool.properties
Added a command line option that allows the user to skip updating OPatch version even if there is a newer one available.  Use of this option requires knowledge of the patches being applied and whether the version of OPatch is sufficient.
> allow the user to skip update for OPatch version, --skipOpatchUpdate

- imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/ProvidedResponseFile.java
- imagetool/src/test/java/com/oracle/weblogic/imagetool/installer/ResponseFileTest.java
- imagetool/src/test/resources/responseFiles/responseA.txt
Fixes #159 
When installer response file names originate from different directories, it is possible that they will have the same simple filename.  When copying those response files to the Docker context folder, rename the target file as needed to accommodate any number of response files that have the same "original" simple name.
> installer response file names may have the same name

- imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/DefaultResponseFile.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java
temp directory on Windows platform not removed because files in the directory were left open.
> Fix problems removing temp context directory on Windows platform

- site/create-image-with-internet.md
I did not look to see that there were different CLA for each password type when following the sample create image documentation. Clarifying for any others like me.
> Clarify password command line arguments for create sample

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/ResolverOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/VerrazzanoModel.java
- imagetool/src/main/resources/ImageTool.properties
- imagetool/src/test/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptionsTest.java
- imagetool/src/test/resources/templates/resolver.yml
- imagetool/src/test/resources/templates/verrazzano.yml
Resolve the parameters in the list of mustache templates specified with new command line argument --resolveFiles. This command line argument takes a comma separated list of path/file names.
The options used to resolve the parameters are from knowledge that the image tool has, such as from the input on the command line.
The options are contained in a single generic file, but can be broken out into multiple files as the mustache command takes in a list of option files.
> resolve parameters in template files with image knowledge

- imagetool/src/main/bin/logging.properties
- imagetool/src/main/java/com/oracle/weblogic/imagetool/logging/AnsiColor.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/logging/ConsoleFormatter.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/logging/FileFormatter.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/logging/LoggingFacade.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/logging/LoggingFactory.java
- imagetool/src/main/resources/ImageTool.properties
Adding color to the console logger makes it easier to see key data in the user's console.
> Support for Ansi colors in console logger

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/cache/AddPatchEntry.java
- imagetool/src/main/resources/ImageTool.properties
- site/cache.md
- tests/src/test/java/com/oracle/weblogic/imagetool/tests/BaseTest.java
- tests/src/test/java/com/oracle/weblogic/imagetool/tests/ITImagetool.java
The --type argument for AddPatchEntry was never used and is causing confusion to the users since the additional installer types were added.
> Deprecated --type argument for AddPatchEntry

- pom.xml
The Guava security issue fixed in v24.1.1 mainly affects long-running server technologies like application servers.  The dependency checker flagged this issue this morning.  Uptake of newer Guava version to ensure users are protected.
> Update Guava dependency to pickup security fixes

- Jenkinsfile
- pom.xml
- tests/src/test/java/com/oracle/weblogic/imagetool/tests/ITImagetool.java
Separated tests by tag, nightly and gate.  Gate tests should run for every PR and gate merges to master.  Nightly tests will run all system tests once every weekday.  
Also, for branches with documentation ONLY checkins. the commit keyword [skip-ci] can be used to omit the running of tests.  This is intended to be used for branches where documentation will be merged just before the release.  Currently, each branch merge requires a merge from master, and a full system test run.  To create a release with 3 new documentation branches takes ~5 hours, today.
> Added nightly builds with full system tests to Jenkins

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/WdtOptions.java
When running updateImage with wdtModelOnly, the check for an existing domain in the base image should not be called.
> fixed issue preventing update image when doing wdtModelOnly

- Jenkinsfile
- build-tools/pom.xml
- installer/pom.xml
- pom.xml
GitHub did not provide URL interface that the WKO system tests could consume.  For now, abandoning maven deploy in favor of OCI object store for the WKO system test artifacts.
> remove github deploy in favor of push to OCI for SNAPSHOT installer

- imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/FmwInstallerType.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/InstallerType.java
- site/create-image.md
- site/rebase-image.md
Allow the user to have Slim, Dev, and normal WLS installers in their cache for a given version of WLS.
> added WLS installer types for the slim and development installers

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java
- imagetool/src/main/resources/docker-files/Update_Image.mustache
Change default for chown to oracle:root instead of oracle:oracle in order to match published Docker images for WebLogic Server.
> default chown to oracle:root 

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java
- imagetool/src/main/resources/ImageTool.properties
- imagetool/src/main/resources/probe-env/test-update-env.sh
When updating an image with UPDATE, if the chown of the update is not the same as what was used during the create, the update will fail with a directory permissions error.  This change detects the chown value that was used during the CREATE, and exits with a error and a clean description of what the user needs to do to get the update to work.
> during updateImage, detect fromImage user and group setting on Oracle Home

- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java
- imagetool/src/main/resources/docker-files/Create_Image.mustache
- imagetool/src/main/resources/docker-files/Update_Image.mustache
This change is trying to avoid the problem where an additional COPY step is added to the end of the Dockerfile that causes the Docker build to fail with missing layer error.  This only fails on some versions of Docker (and perhaps only some versions of host OS).  It looks like a docker bug that we can workaround by optimizing the final build step copy logic to not copy the WDT home again if it has already been copied (under WDT home).  It is unclear why this works.
> Fixfinalcopy

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cachestore/OPatchFile.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
- imagetool/src/test/java/com/oracle/weblogic/imagetool/cachestore/OPatchFileTest.java
Detection of OPatch patches was limited to the bug number.  If the user provided the bug number plus the version, it circumvented the check.  28186730 and 28186730_* should now be skipped. Fixes #219
> Opatch patch detect

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java
- imagetool/src/main/resources/docker-files/Create_Image.mustache
- imagetool/src/main/resources/docker-files/Rebase_Image.mustache
- imagetool/src/main/resources/docker-files/Update_Image.mustache
Allow user to override the default behavior for OPatch patching in order to apply each patch one at a time.  The default behavior is to send all requested patches to OPatch and use napply to add them in a single pass.  Using the new feature --strictPatchOrdering changes the default behavior and uses OPatch apply (instead of napply) to add each patch one at a time. Fixes #201
> add feature to enable strict ordering for patching

- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruPatch.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruUtil.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cachestore/OPatchFile.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java
- imagetool/src/test/java/com/oracle/weblogic/imagetool/cachestore/CachedFileTest.java
- imagetool/src/test/java/com/oracle/weblogic/imagetool/cachestore/PatchFileTest.java
- imagetool/src/test/resources/patch-28186730.xml
Newly released OPatch 13.9.4.2.5 created an issue where the Image Tool could not resolve to a single OPatch patch.  Both 13.9.4.2.5 and 13.9.4.2.4 are both listed as available for download.  This fix should allow the user to select the version of OPatch that is desired, as well as default to the recommended OPatch patch from ARU.
> add handling for newly released OPatch patches with new recommended flag

- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruUtil.java
- imagetool/src/test/java/com/oracle/weblogic/imagetool/aru/AruUtilTest.java
Recommended PSU overlay patches include security fixes and should be included in the set of patches returned from --recommendedPatches.  Unfortunately, ARU metadata does not include the recommended overlays unless the release requested is the PSU version, and not the GA version.
> include recommended PSU overlay patches in --recommendedPatches

- imagetool/src/main/resources/docker-files/Create_Image.mustache
- imagetool/src/main/resources/docker-files/Rebase_Image.mustache
- imagetool/src/main/resources/docker-files/Update_Image.mustache
The locales were removed from the Oracle Linux 8-slim image.  Setting LC_ALL in the image ENV is optional, and so removed to make using OL8-slim cleaner.
> Ol8 locale warning

- imagetool/src/main/resources/docker-files/Create_Image.mustache
- imagetool/src/main/resources/docker-files/Rebase_Image.mustache
If the --fromImage contains a /u01 folder, the image create should not fail.  For example, if the user wants to install Java in /u01/java and use this as the --fromImage, the Image Tool should be able to handle this use case.
> allow base image to have an existing /u01 folder

- imagetool/src/main/resources/docker-files/Create_Image.mustache
- imagetool/src/main/resources/docker-files/Rebase_Image.mustache
- imagetool/src/main/resources/docker-files/Update_Image.mustache
Docker has not fixed the bug in the new buildkit for quite some time.  And worse, the new install defaults to enabling the new buildkit feature.  This Docker bug causes the Docker build step in Image Tool to fail with:
`failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to parse stage name "OS_UPDATE": invalid reference format: repository name must be lowercase`
To see the error, the buildkit must be enabled in the Docker preferences/config:
{
"debug": true,
"experimental": false,
"features": {"buildkit": true }
}
> Work-around for Docker bug in BuildKit

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cachestore/OPatchFile.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/WdtOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/ResourceTemplateOptions.java
- site/create-image.md
- site/update-image.md
Provide documentation for --resourceTemplates parameter, and added {{modelHome}} as a new token for resource templates.
> Added modelHome variable for Verrazzano/WKO templates

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/cache/AddInstallerEntry.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/cache/AddPatchEntry.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/cache/CacheAddOperation.java
- imagetool/src/main/resources/ImageTool.properties
Changed ADD behavior slightly.  If the entry being added is an exact match for key and content, the add operation no longer fails.  This allows the same add operation to be run multiple times without failing.  This should help in test and sample scenarios that repeat steps.  When used from the command line, the user in this scenario will receive a message that nothing was changed.
Additionally, `--force` was added as an option to both addPatch and addInstaller to allow the user to override the existing entry with new content without requiring the user to delete the existing entry first.
> Add --force option to addInstaller and addPatch

- imagetool/src/main/resources/docker-files/Create_Image.mustache
- imagetool/src/main/resources/docker-files/Rebase_Image.mustache
yum install will ignore any packages that are already installed.  Since WLS K8s Operator requires `find`, this change will ensure that the find utility is installed even if the base linux distribution changes.
> ensure that all images have findutils installed for k8s operator

- imagetool/src/main/resources/docker-files/Update_Image.mustache
For older versions of WIT, the compiled python classes were not completely removed.  To prevent issues when updating images created with older versions of Image Tool, this fix completely cleans up the WDT install folder before expanding the new installer for imagetool UPDATE.
> when reinstalling WDT with UPDATE, delete old version first

- imagetool/src/main/java/com/oracle/weblogic/imagetool/builder/BuildCommand.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/RebaseImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/WdtOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java
- imagetool/src/main/resources/ImageTool.properties
- imagetool/src/main/resources/docker-files/Create_Image.mustache
- imagetool/src/main/resources/docker-files/Rebase_Image.mustache
- imagetool/src/main/resources/docker-files/Update_Image.mustache
- imagetool/src/main/resources/probe-env/test-update-env.sh
- pom.xml
- site/create-image-with-internet.md
Removed hard references to Docker and replaced with value provided by the command line.  The default value provides the same behavior as previously used in the hard references `docker`.
> Enable experimental Podman support 

- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruPatch.java
- imagetool/src/test/resources/recommended-patches.xml
Stack Patch Bundle (SPB) is not a patch, but a set of patches.  The zip is not packaged as a normal patch.  And, the contents of the SPB are duplicates of patches in the recommended patches list.  ImageTool will continue to use the recommended patches list, and ignore any SPB's listed as recommended patches in the ARU REST response.
> Reject Stack Patch Bundle as a patch from ARU

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/ImageTool.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/InspectImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/OutputFormat.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/RebaseImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java
- imagetool/src/main/resources/inspect-responses/inspect-json.mustache
- imagetool/src/main/resources/probe-env/inspect-image-long.sh
- imagetool/src/main/resources/probe-env/inspect-image.sh
Added a new verb to the image tool that makes is simpler to query a create image for its contents, such as Java version, WebLogic version, WebLogic patches, etc.
``` bash
$ imagetool inspect --image d:12213
{
javaHome: "/u01/jdk", 
javaVersion: "1.8.0_241", 
oracleHome: "/u01/oracle", 
oracleHomeGroup: "oracle", 
oracleHomeUser: "oracle", 
packageManager: "yum", 
wlsVersion: "12.2.1.3.0"
}
```
> new inspect image tool

- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruProduct.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruUtil.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/FmwInstallerType.java
- imagetool/src/test/java/com/oracle/weblogic/imagetool/aru/AruUtilTest.java
- imagetool/src/test/java/com/oracle/weblogic/imagetool/installer/InstallerTest.java
- imagetool/src/test/resources/releases.xml
Added FMW Platform and Java Require Files ARU product IDs for FMW patching.  Recommended patches from Java Required Files and FMW Platform should be included when patching FMW products (except WebLogic Server stand-alone).  Images created with Image Tool prior to this change may not have the recommended FMW Platform and Java Required Files patches from the April 2021 quarterly update.
> Added FMW Platform and Java Require Files ARU product IDs

- Jenkinsfile
- pom.xml
- tests/pom.xml
- tests/src/test/java/com/oracle/weblogic/imagetool/tests/ITImagetool.java
The build will skip the integration tests by default in order to make it simpler for external customers to build the project.
> build will skip integration tests by default 

- CONTRIBUTING.md
- README.md
From Oracle WebLogic Image Tool to WebLogic Image Tool. Not too many instances to fix.
> name change

- imagetool/src/main/bin/imagetool.cmd
- imagetool/src/main/bin/imagetool.sh
- imagetool/src/main/bin/setup.sh
Allow ImageTool home path to have spaces in directory names and removed symbolic link removal from the shell script.
> Allow ImageTool home path to have spaces in directory names

- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruUtil.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/FmwInstallerType.java
- imagetool/src/main/resources/ImageTool.properties
- imagetool/src/test/java/com/oracle/weblogic/imagetool/installer/InstallerTest.java
Allow non-patching operations on images where the installed products cannot be identified through the registry.xml.  Currently, WLS 12.2.1.4-slim installer is failing to add product-family information to the registry.xml.  This missing data prevents Image Tool from identifying the installed products.
This change allows non-patching operations (like WDT commands) to continue when this situation occurs.  If the user tries to patch, Image Tool will exit with an error that gives a better description of the problem.
> Allow non-patching operations on images with unidentified products

- imagetool/src/main/resources/docker-files/Create_Image.mustache
- imagetool/src/main/resources/docker-files/Update_Image.mustache
- imagetool/src/main/resources/docker-files/run-wdt.mustache
- imagetool/src/main/resources/probe-env/inspect-image-long.sh
- imagetool/src/main/resources/probe-env/inspect-image.sh
- tests/src/test/java/com/oracle/weblogic/imagetool/tests/ITImagetool.java
- tests/src/test/java/com/oracle/weblogic/imagetool/tests/utils/UpdateCommand.java
The `rm` command prior to the extract of the zip/tar.gz was lost in a merge for the previous release.  The WDT directory must be removed prior to extracting the new installer to ensure that all compiled python classes are removed from the previous WDT install.
Additionally, the INSPECT tool will now output the version of WDT installed.
> Fix regression with UPDATE where WDT install could not be overwritten

- imagetool/src/main/resources/probe-env/inspect-image-long.sh
- imagetool/src/main/resources/probe-env/inspect-image.sh
Fixes #303.  When JAVA_HOME is set, INSPECT should use JAVA_HOME to determine the version of Java that is installed.  Otherwise, use Java from the PATH.
> Use JAVA_HOME for java version in INSPECT

- imagetool/src/main/resources/probe-env/inspect-image-long.sh
Fixes #307. In some rare cases, a patch description may not be present for a given WLS patch.  This is probably a bug in the patch creation process, but this code change works around the missing description.
> allow for missing patch description in lsinventory response

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java
When the user specifies a proxy value that contains a user credential, do not log the proxy value in any way.
For example, 
``` bash
export http_proxy=http://blah:blah@proxy.mycompany.com:80
```
Should be concealed as:
[INFO   ] Starting build: docker build ... --build-arg http_proxy=********
> conceal http/s proxy value for logging when credential is present in the proxy

- imagetool/src/main/java/com/oracle/weblogic/imagetool/api/model/CommandResponse.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/InvalidCredentialException.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/ImageTool.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/cache/AddEntry.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/cache/AddPatchEntry.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/cache/CacheAddOperation.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/cache/CacheCLI.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/cache/DeleteEntry.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/cache/ListCacheItems.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/InspectImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/RebaseImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java
- imagetool/src/main/resources/ImageTool.properties
- imagetool/src/test/java/com/oracle/weblogic/imagetool/builder/BuilderTest.java
- imagetool/src/test/java/com/oracle/weblogic/imagetool/cli/ImageToolTest.java
- imagetool/src/test/java/com/oracle/weblogic/imagetool/cli/cache/AddPatchEntryTest.java
- imagetool/src/test/java/com/oracle/weblogic/imagetool/util/CloseableListTest.java
If the first argument is not one of create, cache, update, rebase, or help, the usage statement is not displayed.
> Fix usage for invalid first argument

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/KubernetesTarget.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java
- imagetool/src/main/resources/docker-files/Rebase_Image.mustache
- imagetool/src/main/resources/docker-files/final-wdt-copy.mustache
- imagetool/src/main/resources/docker-files/run-wdt.mustache
- tests/src/test/java/com/oracle/weblogic/imagetool/tests/ITImagetool.java
- tests/src/test/java/com/oracle/weblogic/imagetool/tests/utils/CreateCommand.java
Created a new `--target` option that allows the user to specify the target Kubernetes environment.  The options are `Default` and `OpenShift`.  The OpenShift setting changes the domain directory files such that the group permissions for those files will be the same as the user permissions (group writable, in most cases).  Additionally, if the user does not supply the OS group and user setting with `--chown`, the default for this setting is changed from `oracle:oracle` to `oracle:root` to be inline with the expectations of an OpenShift environment.
> Revert domain file permissions to umask 027 with explicit OpenShift override

- imagetool/src/main/resources/docker-files/create-user-group.mustache
Busybox addgroup and adduser will fail if group or user already exist.
> check for user and group existence before adding for BusyBox images

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Constants.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/HttpUtil.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java
Setting the proxy values in the Apache HTTP client builder caused an override of the default behaviors.  Because nonProxyHosts was not being set, the build ignored the java system property.  Removing the manual setting allows the default behavior to consume both http and https proxy values, as well as the nonProxyHosts value.
> Use system settings proxy for Apache HttpClientBuilder

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/inspect/OperatingSystemProperties.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Constants.java
- imagetool/src/main/resources/docker-files/create-user-group.mustache
Alpine is an extension of BusyBox.  This change adds support for Alpine to be used as a `--fromImage` for `createAuxImage`.  For example:
```shell
imagetool.sh createAuxImage --tag aux:1 --wdtModel ./simple1.yaml --fromImage alpine:latest
```
> Add support for Alpine to Auxiliary image creation

- documentation/1.10/content/userguide/tools/create-aux-image.md
- documentation/1.10/content/userguide/tools/create-image.md
- documentation/1.10/content/userguide/tools/rebase-image.md
- documentation/1.10/content/userguide/tools/update-image.md
Fixes #327. `--skipcleanup` documentation has a typo in the name.
> [skip-ci] fix typo in documentation for skipcleanup option

- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java
The latest changes to handling the proxy-related environment variables removed the ability to honor the upper-case version of the variables (HTTP_PROXY, HTTPS_PROXY, and NO_PROXY).  This PR restores that previous functionality.
> allow tool to be able to use both lower-case and upper-case versions of the proxy-related variables

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonCreateOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java
- imagetool/src/main/resources/docker-files/create-user-group.mustache
- imagetool/src/main/resources/docker-files/run-wdt.mustache
When using `--chown oracle:root` or `--target OpenShift`, the group oracle was not defined in the OS when creating the image.  Reuse of those images required that all subsequent image extensions use `--chown oracle:root` or the image build would fail. By creating the OS group `oracle` even if it is not initially needed, subsequent extensions of that base image can be `--chown oracle:root` or omit the `--chown` to use the default `oracle:oracle`.   Additionally, any combination of `--chown` on a new extension image should work as well.
> Always insert the OS group oracle if not already present

- imagetool/src/main/resources/docker-files/package-managers.mustache
See #337.  When creating new images, this change causes the package manager (yum, dnf, or microdnf) to run an update prior to installing WebLogic.  For the time periods where CVE's are fixed but the Oracle Linux Docker image update has not yet been released, this will help ensure that new images have the latest security fixes available from Oracle.
> ensure OS packages are up to date when creating a new image

- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruProduct.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/FmwInstallerType.java
- imagetool/src/test/java/com/oracle/weblogic/imagetool/installer/InstallerTest.java
The OPSS and OWSM recommended patches for WLS were published under separate product IDs from WLS for the January 2021 CPU.  This change will include those recommendations into --recommendedPatches when using FMW installs including upper stack products like SOA, OSB, WC, etc.
> Added automatic patching for OPSS and OWSM into --recommendedPatches for FMW installs

- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruProduct.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/FmwInstallerType.java
- imagetool/src/test/java/com/oracle/weblogic/imagetool/installer/InstallerTest.java
JDBC patch recommendations are now OPatch compatible for WLS/FMW installations.  JDBC released a recommended patch with the Oracle FMW January CPU.
> Added automatic patching for the Oracle JDBC driver into --recommendedPatches for WLS/FMW installs

- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruProduct.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/FmwInstallerType.java
- imagetool/src/test/java/com/oracle/weblogic/imagetool/installer/InstallerTest.java
Fusion Internal Tools product was added back to the quarterly patching process for the Jan CPU.  This change allows --recommendedPatches to find any recommendations in ARU for Fusion Internal Tools associated with the matching FMW release.  This includes Third Party bundles and RDA OFM patches.
> Added automatic patching for the Oracle third party product, Fusion Internal Tools, into --recommendedPatches for WLS/FMW installs

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/cache/AddInstallerEntry.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/WdtBaseOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/WdtFullOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java
- imagetool/src/main/resources/ImageTool.properties
- imagetool/src/main/resources/docker-files/aux-image.mustache
This change allows `createAuxImage` to create auxiliary images without installing WDT (such as models only).  By specifying the command line option `--wdtVersion=NONE`, the WDT installer step for `createAuxImage` is skipped. 
Model, Variable, and Archive files remain optional for `createAuxImage`.
Illegal options:
- `create` using WDT files but wdtVersion set to NONE.
- `createAuxImage` with no WDT files and wdtVersion set to NONE.
A separate PR for the documentation change is required before release.
> Allow createAuxImage to install the WDT installer and the WDT model files separately

- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruUtil.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/RetryFailedException.java
- imagetool/src/main/resources/ImageTool.properties
- imagetool/src/test/java/com/oracle/weblogic/imagetool/aru/AruUtilTest.java
Retrieving WebLogic patch and release metadata has been unreliable for some users.  This change has added macro level retries around the REST calls that retrieve patch and release metadata.
> Added additional retry logic for retrieving Oracle patches

- imagetool/src/main/resources/docker-files/aux-image.mustache
Docker build failed for auxiliary image with option wdtVersion="NONE".  On some combinations of operating systems and Docker versions (and buildkit), the container image build fails with 
_failed to export image: failed to create image: failed to get layer sha256..._.
This change skips the COPY step when no WDT binaries were installed in the intermediate build image.
Jira -OWLS-97125
> Omit WDT binary copy statement in Aux image build when source directory is empty

- Jenkinsfile
- imagetool/pom.xml
- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruUtil.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonPatchingOptions.java
- imagetool/src/test/java/com/oracle/weblogic/imagetool/cli/menu/CommonPatchingOptionsTest.java
- pom.xml
- tests/pom.xml
Using the -D for the xmlReportPath appears to be more reliable at getting Sonar to recognize the coverage reported by Jacoco.  Recommended in reply from SonarScanner team, I dropped all references to xmlReportPath to allow the tool to default.  As long as the default directories are used, this appears to work.
This change, also, removes the test report aggregation step.  There is only one module reporting unit test coverage, and Surefire tests are not generating any reportable coverage.
> another attempt to workaround bug in coverage reporting for Sonar scanner

- documentation/1.11/content/userguide/tools/create-aux-image.md
- documentation/1.11/content/userguide/tools/create-image.md
- documentation/1.11/content/userguide/tools/rebase-image.md
- documentation/1.11/content/userguide/tools/update-image.md
Each stage of the container image build has different environment variables available.  This change documents which environment variables are available in which sections of the additional build commands.
> Document environment variables available to additional build commands

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/AdditionalBuildCommands.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java
- imagetool/src/main/resources/ImageTool.properties
- imagetool/src/test/java/com/oracle/weblogic/imagetool/util/AdditionalBuildCommandsTest.java
- imagetool/src/test/resources/additionalBuildCommands/two-mustache.txt
This change allows the usage of any existing template placeholders currently used by the build from within an additional build command file.  If the user specifies --additionalBuildCommands {file}, placeholders like {{java_home}} or {{oracle_home}} within the {file} provided were not previously resolved.  This change allows the usage of any of the existing placeholders used in the Image Tools templates to be used within the user's {file}.
> allow usage of Mustache placeholders in additional build command file

- imagetool/src/main/resources/ImageTool.properties
- imagetool/src/main/resources/docker-files/run-wdt.mustache
OpenShift certification is failing due to the WKO creating the WDT logs in the wrong folder due to lack of permissions.
> create and allow openshift users to access WDT logs directory when target is OpenShift

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/RebaseImage.java
- imagetool/src/main/resources/ImageTool.properties
Fixes #366. When copying modelOnly from old to new container image, WDT_HOME was not being populated after inspection of the source image.
Additionally, the file ownership for the domain and models was incorrectly using the default values instead of reading the value from the target container image.
> Fixed bug in REBASE that prevented copy of WDT_HOME

- imagetool/src/main/java/com/oracle/weblogic/imagetool/inspect/InspectOutput.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/inspect/OperatingSystemProperties.java
- imagetool/src/main/resources/probe-env/inspect-image-long.sh
- imagetool/src/main/resources/probe-env/inspect-image.sh
If available, INSPECT will include `releasePackage` as an attribute for the OS.  The release package is the package name for the file /etc/os-release.  For the time-being, the usefulness of this attribute may be limited to Oracle Linux.
"os" : {
"id" : "ol",
"name" : "Oracle Linux Server",
"version" : "7.9"
"releasePackage" : "oraclelinux-release-7.9-1.0.9.el7.x86_64"
},
> Added releasePackage attribute to INSPECT image.

- imagetool/src/main/java/com/oracle/weblogic/imagetool/inspect/InspectOutput.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/inspect/OperatingSystemProperties.java
- imagetool/src/test/java/com/oracle/weblogic/imagetool/inspect/InspectTest.java
- imagetool/src/test/resources/inspect/image3.json
- imagetool/src/test/resources/inspect/image3.properties
Fixed the missing comma after the version attribute in OS
```json
"os" : {
"id" : "ol",
"name" : "Oracle Linux Server",
"version" : "8.5",
"releasePackage" : "oraclelinux-release-8.5-1.0.7.el8.x86_64"
},
```
> Fixed invalid output for INSPECT of Oracle Linux images. Missing comma in OS object.

- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java
While using the `--additionalBuildFiles` option it was observed that certain files were not getting copied and the tool was printing always the source directory name and not the actual file name/path that could not be copied. This PR to fix that.
> --additionalBuildFiles should print child file path not being copied

- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruPatch.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruUtil.java
Fixes #394.  With the October PSU, Coherence recommends two patches for 14.1.1, one with an extra feature pack, and both with bug fixes.  Only one patch is applicable.  As a quick fix, the feature pack version of the patch will be ignored.
> ignore coherence feature pack patch when recommended by ARU

- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruPatch.java
Code around ARU changes in bugs that are cancelled, where the download URL is deleted from metadata.  Bug 29135930 has this issue as of today.
> code around ARU changes in bugs that are cancelled

- documentation/1.11/content/developer/contribute.md
- documentation/1.11/content/samples/create-image-wdt.md
- documentation/1.11/content/userguide/tools/create-aux-image.md
Update docs that have changed location.
> fix broken links

- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruProduct.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/DefaultResponseFile.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/FmwInstallerType.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/InstallerType.java
The `--type` option will accept "ohs" as an option.  Using the 12.2.1.3 and 12.2.1.4 GA installers for OHS, the Image Tool will be able to create images with the latest PSUs for Oracle HTTP Server.
> Add support for the Oracle HTTP Server installer

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonPatchingOptions.java
- imagetool/src/test/java/com/oracle/weblogic/imagetool/cli/menu/CommonPatchingOptions2Test.java
There is no need to validate user credentials when no patching operations are going to be performed.  If the user provides `--user` but does NOT provide `--patches` or `--latestPSU` or `--recommendedPatches`, there is no need to validate the user credential.
> Only validate user credentials if there are patches involved.

- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruPatch.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/Version.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
- imagetool/src/test/java/com/oracle/weblogic/imagetool/aru/VersionTest.java
The ARU product version is being compared as string/text, which causes the sorting algorithm to fail for versions like 13.9.2.4.9 and 13.9.2.4.10.  This change is aware of semantic versions and compares the version strings as integers.
> Compare ARU product version numerically

- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/PackageManagerType.java
- imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java
- imagetool/src/main/resources/docker-files/package-managers.mustache
Detect OL8 and do not specify the -y (assume yes) flag when using `microdnf`.  For OL9, `microdnf` must have the `-y`.
> Updated microdnf command line for use with linux 9 which does not assume yes by default
