oracle/weblogic-image-tool

imagetool/src/main/resources/docker-files/Dockerfile.create
=> WLS install should ignore prerequisites

site/quickstart.md
Some of these are a re-do of edits I suggested previously, some are new. Most are provided to fine tune your doc and align it with Oracle style guidelines.
=> additional edits

imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/ARUUtil.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Constants.java
This fixes problem with creating or updating fmw with latestPSU.  It should first patch for WLS and not just relying on the fmw product.
=> Fix FMW image with latestPSU, it should include base WLS also.

imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/ImageOperation.java, imagetool/src/main/resources/docker-files/Create_Image.mustache, imagetool/src/main/resources/docker-files/Update_Image.mustache
Allow custom user/group for owner of install and patches. Fixes #20
=> Derek custom userid groupid

imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/ImageOperation.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java
Reduce conversions back and forth from String to Path, and remove duplicate code blocks.
=> reduce duplicate code 

imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/ImageOperation.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/logging/FileFormatter.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java, imagetool/src/main/resources/docker-files/Create_Image.mustache, imagetool/src/main/resources/docker-files/Update_Image.mustache, imagetool/src/test/java/com/oracle/weblogic/imagetool/integration/ITImagetool.java
Add multiple models support for WDT
=> Wdtmodelistfix

.gitignore, .idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, imagetool/src/main/bin/logging.properties, imagetool/src/main/java/com/oracle/weblogic/imagetool/api/model/AbstractFile.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/CLIDriver.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/cache/AddPatchEntry.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/ImageOperation.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/impl/InstallerFile.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/impl/PatchFile.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/logging/FileFormatter.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/logging/LoggingFacade.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/logging/LoggingFactory.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/ARUUtil.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/HttpUtil.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/XPathUtil.java, imagetool/src/main/resources/ImageTool.properties
=> Adding logging framework to support i18n

imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java, imagetool/src/main/resources/ImageTool.properties
=> Corrected patch format message

imagetool/src/main/resources/docker-files/Create_Image.mustache
=> merge error, fix chown for patching COPY

imagetool/src/main/bin/logging.properties, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/ImageOperation.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java, imagetool/src/main/resources/ImageTool.properties, imagetool/src/main/resources/docker-files/Create_Image.mustache, site/quickstart.md
=> Added support to override FMW installer response file.

imagetool/src/main/java/com/oracle/weblogic/imagetool/util/HttpUtil.java
Enhance the error message for HttpUtil.downloadFile
=> Enhance error message for HttpUtil.downloadFile

README.md, imagetool/src/assembly/zip.xml, imagetool/src/main/bin/imagetool.cmd, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/ImageOperation.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java, site/quickstart.md
Add support to run the tool in Windows environment
=> Windows support

imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/ImageOperation.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java, imagetool/src/main/resources/docker-files/Create_Image.mustache, imagetool/src/main/resources/docker-files/Update_Image.mustache, site/create-image.md, site/update-image.md
Instead of creating a domain in image, allow the user to add WDT with models and archive to the image without creating the domain.
=> Allow Model in Image use case

imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/ImageOperation.java
Latest model in image push broke variable file argument passing to docker build.
=> correct regression with WDT variable file argument in docker build

imagetool/src/main/bin/imagetool.sh, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java
Added alternative to alias for starting the image tool.  This PR adds a simple unix script that sets the classpath and executes the Java tool.
=> added optional unix script to run imagetool

imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/ImageOperation.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/logging/LoggingFacade.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/ARUUtil.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Constants.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/HttpUtil.java, imagetool/src/main/resources/ImageTool.properties
- Fixes error "FMW installer is required for JRF domain" when using WDT to create a JRF domain.
- Fixes ability to apply JRF latestPSU and patches for JRF installers
=> fix patch handling for JRF installers

imagetool/pom.xml, imagetool/src/test/java/com/oracle/weblogic/imagetool/integration/BaseTest.java
update the tests to use imagetool.zip
=> Imagetooltest2

imagetool/src/main/java/com/oracle/weblogic/imagetool/api/model/DomainType.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/ImageOperation.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java, imagetool/src/main/resources/docker-files/Create_Image.mustache, imagetool/src/main/resources/docker-files/Update_Image.mustache
Default installer to FMW if not a WLS domain type in WDT param.  Fix  run RCU param.
=> fix WDT RCU parameter

Jenkinsfile, imagetool/src/test/java/com/oracle/weblogic/imagetool/integration/BaseTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/integration/ITImagetool.java
=> Use new wlsimgcachedir

imagetool/src/test/java/com/oracle/weblogic/imagetool/api/model/DomainTypeTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/cli/cache/AddEntryTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/cli/cache/AddInstallerEntryTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/impl/meta/FileCacheStoreTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/integration/BaseTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/integration/ITImagetool.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/integration/utils/ExecCommand.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/integration/utils/ExecResult.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/util/UtilsTest.java, pom.xml
enabled Checkstyle for test sources
=> cleanup test src for Checkstyle/Sonar formatting and copyright headers

README.md, site/argument-file.md, site/cache.md, site/cleanup.md, site/create-image-no-internet.md, site/create-image-wdt.md, site/create-image-with-internet.md, site/logging.md, site/patching-image.md, site/quickstart.md
I revised the Image Tool docs as we discussed. One item that was not done was to add cross-references to the Argument File doc in the Create Tool and Update Tool docs (because I didn't have their latest versions, I was afraid to edit them.) I can make those final edits after this PR is reviewed, edited, if needed, and merged.
=> revise docs

README.md, site/create-image-with-internet.md, site/create-image.md, site/quickstart.md, site/update-image.md
1. Added "Use an arguments file" to the Additional Information section in the Create and Update Tool docs.
2. Fixed the link to the Additional Information section in both docs.
3. Minor cleanup of text where needed (mostly removed hyphens).
=> added args file info

build-tools/pom.xml, pom.xml
Should have updated version of build-tools for new copyright checkstyle pattern
=> updated version of build-tools for new copyright checkstyle pattern

imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/ImageOperation.java
This fix refactor and enable multiple archives passed in --wdtArchive in create or update.
=> #100  Enable multiple archives for WDT create or update

imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/ImageOperation.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/impl/PatchFile.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java, imagetool/src/main/resources/ImageTool.properties, imagetool/src/main/resources/docker-files/Create_Image.mustache
OPatch patching itself with custom patch jar is not making it into the image.
=> fix new OPatch Patch installer

build-tools/src/main/resources/weblogic-image-tool/checkstyle/customized_google_checks.xml, imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/MiddlewareInstall.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/logging/LoggingFacade.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/ARUUtil.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java, pom.xml
Update Checkstyle to version 8.29
=> update checkstyle plugin to 8.29 and codestyle XML to newest release

README.md, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/cache/ListCacheItems.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/WLSInstallHelper.java, site/argument-file.md, site/cache.md, site/cleanup.md, site/create-image-no-internet.md, site/create-image-wdt.md, site/create-image-with-internet.md, site/create-image.md, site/logging.md, site/patching-image.md, site/quickstart.md, site/rebase-image.md, site/update-image.md
Reviewing files that were updated for the upcoming release but didn't get the copyright updated.
=> update copyright for changed files before release

imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/RebaseImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/WdtOptions.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Constants.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerBuildCommand.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java, imagetool/src/main/resources/docker-files/Create_Image.mustache, imagetool/src/main/resources/docker-files/Update_Image.mustache
Documentation will be merged separately.
=> added support for WDT use_encryption flag

imagetool/pom.xml, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/WLSCommandLine.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/cachestore/meta/FileCacheStoreTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/cli/cache/AddEntryTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/cli/cache/AddInstallerEntryTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/integration/ITImagetool.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/util/AdditionalBuildCommandsTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/util/DockerfileBuilderTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/util/UtilsTest.java, pom.xml
Upgrade test framework to JUnit 5
=> upgrade from JUnit 4 to JUnit 5

imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerBuildCommand.java
Allow network parameter for Docker to be passed to docker build command.
=> added container network feature to build

imagetool/src/main/java/com/oracle/weblogic/imagetool/cachestore/CacheStoreFactory.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/WLSInstallHelper.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/api/model/CachedFileTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/cachestore/CacheStoreImpl.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/cachestore/CacheStoreTestImpl.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/cachestore/FileCacheStoreTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/cachestore/PatchFileTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/util/UtilsTest.java
Adding unit tests for system proxy util method, and CachedFile / PatchFile.
=> Added unit tests for CachedFile and PatchFile

imagetool/src/main/java/com/oracle/weblogic/imagetool/api/model/CachedFile.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cachestore/PatchFile.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Constants.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/HttpUtil.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/api/model/CachedFileTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/cachestore/CacheStoreTestImpl.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/cachestore/PatchFileTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/wdt/WdtUnitTest.java, imagetool/src/test/resources/patch-1110001.xml, imagetool/src/test/resources/patch-1110002.xml
Added unit tests for WDT enum classes.
Added unit tests for PatchFile methods that parse ARU XML responses.
=> Added unit tests for PatchFile ARU parsing operations

imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java, imagetool/src/main/resources/docker-files/Rebase_Image.mustache
Copied the logic from the Create template into the Rebase template for the inventory location handling.
=> fix inventory location handling for Rebase

imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/WdtOptions.java, imagetool/src/main/resources/ImageTool.properties, imagetool/src/main/resources/probe-env/test-create-env.sh, imagetool/src/main/resources/probe-env/test-update-env.sh
improve error message when WDT Operation UPDATE is used on image without a domain. Fixes #170
=> improve error message for WDT UPDATE when image has no domain

imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/WdtOptions.java
Allows "model in archive" to work with Image Tool
=> Allow archive with model option for WDT

imagetool/pom.xml, imagetool/src/main/resources/VERSION.txt, installer/src/assembly/zip.xml
Already a file about the project itself called version-info.properties. Add VERSION.txt to include in the install archive. This matches LICENSE.txt that already exists in the install archive
=> Add a new version file to install image

imagetool/src/main/resources/docker-files/Create_Image.mustache
Tests for directory name before moving the extracted JDK to JAVA_HOME
=> Added support for using the GraalVM JDK installer

imagetool/src/main/resources/docker-files/Rebase_Image.mustache
REBASE should be adding DOMAIN_HOME environment variable to the resulting image. Fixes #193
=> add DOMAIN_HOME environment variable for REBASE

imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/WdtOptions.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java, imagetool/src/main/resources/docker-files/Create_Image.mustache, imagetool/src/main/resources/docker-files/Update_Image.mustache
Please review and this still depends on the pending WDT changes. Fixes #190
=> #190 - support configurable model home location

imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/PackageManagerType.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java, imagetool/src/main/resources/docker-files/Create_Image.mustache, imagetool/src/main/resources/docker-files/Rebase_Image.mustache, imagetool/src/main/resources/probe-env/test-create-env.sh, imagetool/src/main/resources/probe-env/test-update-env.sh
Added package manager types for DNF MicroDNF.
=> moved package manager detection into environment probe

imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/AruProduct.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/FmwInstallerType.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/installer/InstallerTest.java
RecommendedPatches and LatestPSU should include the JDeveloper product PSU for all FMW installs.
=> added JDeveloper product patches to FMW install types 

imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java, imagetool/src/main/resources/docker-files/Create_Image.mustache, imagetool/src/main/resources/docker-files/Rebase_Image.mustache, imagetool/src/main/resources/docker-files/Update_Image.mustache
Opened group write permissions on WDT, WebLogic Server domain, and WDT models folders.
=> Add group permissions to domain and model folders

imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/FmwInstallerType.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/InstallerType.java, imagetool/src/main/resources/ImageTool.properties, imagetool/src/test/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptionsTest.java
Temporary workaround to skip ADR patch if recommended for WLS installer type
=> temporary workaround to skip ADR patch if recommended for WLS

imagetool/src/main/resources/docker-files/Create_Image.mustache, imagetool/src/main/resources/docker-files/Rebase_Image.mustache, imagetool/src/main/resources/docker-files/Update_Image.mustache
Fix several installed files that do not have group read permissions in the Oracle Home.
=> Fix installed files that do not have group read permissions in the OH

.gitignore, Jenkinsfile, imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruUtil.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Constants.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/HttpUtil.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/aru/AruUtilTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/cli/cache/AddPatchEntryTest.java, imagetool/src/test/resources/releases.xml, tests/pom.xml, tests/src/test/java/com/oracle/weblogic/imagetool/tests/ITImagetool.java
- Added a couple of additional unit tests.
- Moved database image pull to Dockerfile
- Removed dependency on additional OS image
- Changed constants to support testing ARU in UAT
=> Additional unit tests

site/create-image.md, site/rebase-image.md, site/update-image.md
Added more detail regarding the additional build commands file sections.
=> [skip-ci] clarify documentation on additional build commands file

imagetool/src/main/java/com/oracle/weblogic/imagetool/util/AdditionalBuildCommands.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java, imagetool/src/main/resources/ImageTool.properties, imagetool/src/main/resources/docker-files/Create_Image.mustache
Added support for adding additional OS packages with `--additionalBuildCommands`
Fixes #214.
=> added support for adding additional OS packages

site/create-image.md
Documentation for adding additional OS packages to AdditionalBuildCommands
=> DOC for adding additional OS packages 

imagetool/src/main/resources/docker-files/Create_Image.mustache, imagetool/src/main/resources/docker-files/Update_Image.mustache, tests/src/test/java/com/oracle/weblogic/imagetool/tests/ITImagetool.java, tests/src/test/java/com/oracle/weblogic/imagetool/tests/utils/CreateCommand.java
OEL 8-slim has removed the command "find".  To support OEL 8-slim base images, this change replaces the "find" command used to remove *.class files from the WDT Jython run.
=> replace find command in Jenkinsfile

pom.xml
Updated Mustache dependency from 0.9.6 to 0.9.7.
=> update mustache version to 0.9.7

imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruUtil.java
Alter XPath to be able to locate JDeveloper PSU releases.
=> Unable to locate PSU for JDeveloper

imagetool/src/main/java/com/oracle/weblogic/imagetool/util/HttpUtil.java
ARU will be updating its web gate in March.  This change is necessary for continued use of the ARU patches REST services.
=> Support new Oracle updates site security gate

imagetool/src/main/java/com/oracle/weblogic/imagetool/builder/BuildCommand.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/RebaseImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/UpdateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/WdtOptions.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java, imagetool/src/main/resources/ImageTool.properties, imagetool/src/main/resources/docker-files/Create_Image.mustache, imagetool/src/main/resources/docker-files/Rebase_Image.mustache, imagetool/src/main/resources/docker-files/Update_Image.mustache, imagetool/src/main/resources/probe-env/test-update-env.sh
Fixes #253. Allow images with WDT model only to use REBASE.
=> Added support for WDT model only to REBASE operation

imagetool/src/main/resources/docker-files/Create_Image.mustache, imagetool/src/main/resources/docker-files/Rebase_Image.mustache, imagetool/src/main/resources/docker-files/Update_Image.mustache, imagetool/src/main/resources/docker-files/create-user-group.mustache, imagetool/src/main/resources/docker-files/fmw-patching.mustache, imagetool/src/main/resources/docker-files/package-managers.mustache
The version of mustache we use supports "includes".  This change introduces that functionality for a couple of blocks of code.   This "include" feature could be used a bit more with future changes.
=> no functional changes, introduced reusable mustache templates

imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/HelpVersionProvider.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java
Log the tool version to help with debugging.
```
[INFO   ] WebLogic Image Tool version 1.9.11
```
=> Log the tool version to stdout and log for create/update/rebase

imagetool/src/main/java/com/oracle/weblogic/imagetool/util/HttpUtil.java
increase number of time to retry on OraClient. Wrap conflict check in a retry. Don't do a wait since timeout on sockect and connect
=> change number of retries. Wrap other request in retry

imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java, imagetool/src/main/resources/docker-files/final-wdt-copy.mustache, tests/src/test/java/com/oracle/weblogic/imagetool/tests/ITImagetool.java
fix directory permissions for domain parent  to be group writable and add directory permissions to integration test
=> fix directory permissions for domain parent 

imagetool/src/main/java/com/oracle/weblogic/imagetool/util/HttpUtil.java
This fixes when client has no proxy is set where we removed the default credential provider
=> Fix no proxy authenticaiton failure

documentation/1.9/content/userguide/tools/create-image.md, documentation/1.9/content/userguide/tools/rebase-image.md, documentation/1.9/content/userguide/tools/update-image.md
Documents the --builder option.
=> Update doc to include podman builder CLI

documentation/1.9/content/userguide/tools/inspect-image.md
Documentation for the inspect image feature
=> Documentation for the inspect image feature

imagetool/src/main/java/com/oracle/weblogic/imagetool/inspect/InspectOutput.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/inspect/InventoryPatch.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/inspect/OperatingSystemProperties.java, imagetool/src/main/resources/probe-env/inspect-image-long.sh, imagetool/src/main/resources/probe-env/inspect-image.sh, imagetool/src/test/resources/inspect/image1.json, imagetool/src/test/resources/inspect/image1.properties, imagetool/src/test/resources/inspect/image2.json, imagetool/src/test/resources/inspect/image2.properties
`
{
"os" : {
"id" : "ol",
"name" : "Oracle Linux Server",
"version" : "8.4"
},
"packageManager" : "MICRODNF"
}`
=> Added OS values to inspect feature

tests/src/test/java/com/oracle/weblogic/imagetool/tests/ITImagetool.java
Added additional checks to the system test for file permissions for WDT model-only.
=> added additional checks to the system test for file permissions 

imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruPatch.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptions.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/CreateImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/menu/RebaseImage.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/inspect/InspectOutput.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/MiddlewareInstall.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/logging/ConsoleFormatter.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/Utils.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/aru/InstalledPatchTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/cachestore/CachedFileTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/cachestore/OPatchFileTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/cachestore/PatchFileTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/cli/cache/AddPatchEntryTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptionsTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/inspect/InspectTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/installer/InstallerTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/installer/ResponseFileTest.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/wdt/WdtUnitTest.java, tests/pom.xml
Changed argLine to correct reporting for static code coverage.  Also included minor code cleanup of unused code and naming issues.
=> fix code coverage reporting

imagetool/src/main/resources/docker-files/run-wdt.mustache
This fixes run-wdt mustache file hard coded wdt command.
=> Fixes run-wdt mustache hard coded wdt command

pom.xml
Update JUnit dependency to latest and keep in sync with other projects.
=> update to latest JUnit 5.8.1

documentation/1.10/content/userguide/tools/create-aux-image.md
Document additionalBuildCommands and additionalBuildFiles for the createAuxImage use case.
=> documentation for additionalBuildCommands for createAuxImage

documentation/1.11/content/_index.md
Updated the docs as per JIRA [OWLS-97338](https://jira.oraclecorp.com/jira/browse/OWLS-97338): WIT - Document FMW lists products that are supported by the Image Tool. After Monica updates the FMW OPatch documentation, I will add a x-ref to it.
=> FMW product support

documentation/1.11/content/userguide/tools/create-aux-image.md, documentation/1.11/content/userguide/tools/create-image.md, documentation/1.11/content/userguide/tools/inspect-image.md, documentation/1.11/content/userguide/tools/rebase-image.md, documentation/1.11/content/userguide/tools/update-image.md
Bit of cleanup for some command options and elsewhere.
=> edits per Derek, plus some

imagetool/src/main/java/com/oracle/weblogic/imagetool/aru/AruProduct.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/cli/cache/CacheCLI.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/installer/FmwInstallerType.java, imagetool/src/test/java/com/oracle/weblogic/imagetool/cli/menu/CommonOptionsTest.java, pom.xml
With v10 of checkstyle, several checks started working that appear to have been skipped in the older release.
=> Fixes for checkstyle scan, and prepare for uptake of checkstyle v10

.github/release.yml, Jenkinsfile
Two step release was failing in build with "release not found".  One-step release works.
=> use single step to create draft release with artifacts

documentation/1.11/content/userguide/tools/create-aux-image.md, documentation/1.11/content/userguide/tools/create-image.md, documentation/1.11/content/userguide/tools/rebase-image.md, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/AdditionalBuildCommands.java, imagetool/src/main/java/com/oracle/weblogic/imagetool/util/DockerfileOptions.java, imagetool/src/main/resources/docker-files/Create_Image.mustache, imagetool/src/main/resources/docker-files/Rebase_Image.mustache, imagetool/src/main/resources/docker-files/aux-image.mustache
Added additional build command hook for --additionalBuildCommands prior at the beginning of the Dockerfile, initial-build-commands
=> Added additional build command hook, initial-build-commands

Jenkinsfile
Fixed Jenkinsfile build to correctly derive version number from the release tag.
=> Fixed tag version number derivation for publishing draft release
